-- CreateTable
CREATE TABLE `players` (
    `player_id` INTEGER NOT NULL,
    `team_id` INTEGER NULL,
    `league_id` INTEGER NULL,
    `position` SMALLINT NULL,
    `role` SMALLINT NULL,
    `first_name` VARCHAR(50) NULL,
    `last_name` VARCHAR(50) NULL,
    `nick_name` VARCHAR(50) NULL,
    `age` SMALLINT NULL,
    `date_of_birth` DATE NULL,
    `city_of_birth_id` INTEGER NULL,
    `nation_id` INTEGER NULL,
    `second_nation_id` INTEGER NULL,
    `weight` SMALLINT NULL,
    `height` SMALLINT NULL,
    `retired` TINYINT NULL,
    `free_agent` TINYINT NULL,
    `last_league_id` INTEGER NULL,
    `last_team_id` INTEGER NULL,
    `organization_id` INTEGER NULL,
    `last_organization_id` INTEGER NULL,
    `language_ids0` INTEGER NULL,
    `language_ids1` INTEGER NULL,
    `uniform_number` SMALLINT NULL,
    `experience` SMALLINT NULL,
    `person_type` SMALLINT NULL,
    `bats` SMALLINT NULL,
    `throws` SMALLINT NULL,
    `personality_greed` SMALLINT NULL,
    `personality_loyalty` SMALLINT NULL,
    `personality_play_for_winner` SMALLINT NULL,
    `personality_work_ethic` SMALLINT NULL,
    `personality_intelligence` SMALLINT NULL,
    `personality_leader` SMALLINT NULL,
    `historical_id` VARCHAR(50) NULL,
    `historical_team_id` VARCHAR(50) NULL,
    `best_contract_offer_id` INTEGER NULL,
    `injury_is_injured` TINYINT NULL,
    `injury_dtd_injury` TINYINT NULL,
    `injury_career_ending` TINYINT NULL,
    `injury_dl_left` SMALLINT NULL,
    `injury_dl_playoff_round` SMALLINT NULL,
    `injury_left` SMALLINT NULL,
    `dtd_injury_effect` SMALLINT NULL,
    `dtd_injury_effect_hit` SMALLINT NULL,
    `dtd_injury_effect_throw` SMALLINT NULL,
    `dtd_injury_effect_run` SMALLINT NULL,
    `injury_id` SMALLINT NULL,
    `injury_id2` SMALLINT NULL,
    `injury_dtd_injury2` TINYINT NULL,
    `injury_left2` SMALLINT NULL,
    `dtd_injury_effect2` SMALLINT NULL,
    `dtd_injury_effect_hit2` SMALLINT NULL,
    `dtd_injury_effect_throw2` SMALLINT NULL,
    `dtd_injury_effect_run2` SMALLINT NULL,
    `prone_overall` SMALLINT NULL,
    `prone_leg` SMALLINT NULL,
    `prone_back` SMALLINT NULL,
    `prone_arm` SMALLINT NULL,
    `fatigue_pitches0` SMALLINT NULL,
    `fatigue_pitches1` SMALLINT NULL,
    `fatigue_pitches2` SMALLINT NULL,
    `fatigue_pitches3` SMALLINT NULL,
    `fatigue_pitches4` SMALLINT NULL,
    `fatigue_pitches5` SMALLINT NULL,
    `fatigue_points` SMALLINT NULL,
    `fatigue_played_today` TINYINT NULL,
    `running_ratings_speed` SMALLINT NULL,
    `running_ratings_stealing` SMALLINT NULL,
    `running_ratings_baserunning` SMALLINT NULL,
    `college` TINYINT NULL,
    `acquired` SMALLINT NULL,
    `acquired_date` DATE NULL,
    `draft_year` SMALLINT NULL,
    `draft_round` SMALLINT NULL,
    `draft_supplemental` TINYINT NULL,
    `draft_pick` SMALLINT NULL,
    `draft_overall_pick` SMALLINT NULL,
    `draft_eligible` TINYINT NULL,
    `hsc_status` SMALLINT NULL,
    `redshirt` TINYINT NULL,
    `picked_in_draft` TINYINT NULL,
    `school` SMALLINT NULL,
    `commit_school` SMALLINT NULL,
    `hidden` TINYINT NULL,
    `draft_league_id` INTEGER NULL,
    `draft_team_id` INTEGER NULL,
    `turned_coach` TINYINT NULL,
    `hall_of_fame` TINYINT NULL,
    `rust` SMALLINT NULL,
    `inducted` SMALLINT NULL,
    `strategy_override_team` TINYINT NULL,
    `strategy_stealing` INTEGER NULL,
    `strategy_running` INTEGER NULL,
    `strategy_bunt_for_hit` INTEGER NULL,
    `strategy_sac_bunt` INTEGER NULL,
    `strategy_hit_run` INTEGER NULL,
    `strategy_hook_start` INTEGER NULL,
    `strategy_hook_relief` INTEGER NULL,
    `strategy_pitch_count` INTEGER NULL,
    `strategy_pitch_around` INTEGER NULL,
    `strategy_never_pinch_hit` TINYINT NULL,
    `strategy_defensive_sub` TINYINT NULL,
    `strategy_dtd_sit_min` TINYINT NULL,
    `strategy_dtd_allow_ph` TINYINT NULL,
    `local_pop` SMALLINT NULL,
    `national_pop` SMALLINT NULL,
    `draft_protected` TINYINT NULL,
    `morale` SMALLINT NULL,
    `morale_player_performance` SMALLINT NULL,
    `morale_team_performance` SMALLINT NULL,
    `morale_team_transactions` SMALLINT NULL,
    `expectation` SMALLINT NULL,
    `morale_player_role` SMALLINT NULL,
    `on_loan` TINYINT NULL,
    `loan_league_id` INTEGER NULL,
    `loan_team_id` INTEGER NULL,

    PRIMARY KEY (`player_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `players_batting` (
    `player_id` INTEGER NOT NULL,
    `team_id` INTEGER NULL,
    `league_id` INTEGER NULL,
    `position` SMALLINT NULL,
    `role` SMALLINT NULL,
    `batting_ratings_overall_contact` SMALLINT NULL,
    `batting_ratings_overall_gap` SMALLINT NULL,
    `batting_ratings_overall_eye` SMALLINT NULL,
    `batting_ratings_overall_strikeouts` SMALLINT NULL,
    `batting_ratings_overall_hp` SMALLINT NULL,
    `batting_ratings_overall_power` SMALLINT NULL,
    `batting_ratings_overall_babip` SMALLINT NULL,
    `batting_ratings_vsr_contact` SMALLINT NULL,
    `batting_ratings_vsr_gap` SMALLINT NULL,
    `batting_ratings_vsr_eye` SMALLINT NULL,
    `batting_ratings_vsr_strikeouts` SMALLINT NULL,
    `batting_ratings_vsr_hp` SMALLINT NULL,
    `batting_ratings_vsr_power` SMALLINT NULL,
    `batting_ratings_vsr_babip` SMALLINT NULL,
    `batting_ratings_vsl_contact` SMALLINT NULL,
    `batting_ratings_vsl_gap` SMALLINT NULL,
    `batting_ratings_vsl_eye` SMALLINT NULL,
    `batting_ratings_vsl_strikeouts` SMALLINT NULL,
    `batting_ratings_vsl_hp` SMALLINT NULL,
    `batting_ratings_vsl_power` SMALLINT NULL,
    `batting_ratings_vsl_babip` SMALLINT NULL,
    `batting_ratings_talent_contact` SMALLINT NULL,
    `batting_ratings_talent_gap` SMALLINT NULL,
    `batting_ratings_talent_eye` SMALLINT NULL,
    `batting_ratings_talent_strikeouts` SMALLINT NULL,
    `batting_ratings_talent_hp` SMALLINT NULL,
    `batting_ratings_talent_power` SMALLINT NULL,
    `batting_ratings_talent_babip` SMALLINT NULL,
    `batting_ratings_misc_bunt` SMALLINT NULL,
    `batting_ratings_misc_bunt_for_hit` SMALLINT NULL,
    `batting_ratings_misc_gb_hitter_type` SMALLINT NULL,
    `batting_ratings_misc_fb_hitter_type` SMALLINT NULL,

    PRIMARY KEY (`player_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `players_career_batting_stats` (
    `player_id` INTEGER NOT NULL,
    `year` SMALLINT NULL,
    `team_id` INTEGER NULL,
    `game_id` INTEGER NULL,
    `league_id` INTEGER NULL,
    `level_id` SMALLINT NULL,
    `split_id` SMALLINT NULL,
    `position` SMALLINT NULL,
    `ab` SMALLINT NULL,
    `h` SMALLINT NULL,
    `k` SMALLINT NULL,
    `pa` SMALLINT NULL,
    `pitches_seen` SMALLINT NULL,
    `g` SMALLINT NULL,
    `gs` SMALLINT NULL,
    `d` SMALLINT NULL,
    `t` SMALLINT NULL,
    `hr` SMALLINT NULL,
    `r` SMALLINT NULL,
    `rbi` SMALLINT NULL,
    `sb` SMALLINT NULL,
    `cs` SMALLINT NULL,
    `bb` SMALLINT NULL,
    `ibb` SMALLINT NULL,
    `gdp` SMALLINT NULL,
    `sh` SMALLINT NULL,
    `sf` SMALLINT NULL,
    `hp` SMALLINT NULL,
    `ci` SMALLINT NULL,
    `wpa` DOUBLE NULL,
    `stint` SMALLINT NULL,
    `ubr` DOUBLE NULL,
    `war` DOUBLE NULL,

    PRIMARY KEY (`player_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `players_career_fielding_stats` (
    `player_id` INTEGER NOT NULL,
    `year` SMALLINT NULL,
    `team_id` INTEGER NULL,
    `league_id` INTEGER NULL,
    `level_id` SMALLINT NULL,
    `split_id` SMALLINT NULL,
    `position` SMALLINT NULL,
    `tc` SMALLINT NULL,
    `a` SMALLINT NULL,
    `po` SMALLINT NULL,
    `er` SMALLINT NULL,
    `ip` SMALLINT NULL,
    `g` SMALLINT NULL,
    `gs` SMALLINT NULL,
    `e` SMALLINT NULL,
    `dp` SMALLINT NULL,
    `tp` SMALLINT NULL,
    `pb` SMALLINT NULL,
    `sba` SMALLINT NULL,
    `rto` SMALLINT NULL,
    `ipf` SMALLINT NULL,
    `plays` SMALLINT NULL,
    `plays_base` SMALLINT NULL,
    `roe` SMALLINT NULL,
    `opps_0` SMALLINT NULL,
    `opps_made_0` SMALLINT NULL,
    `opps_1` SMALLINT NULL,
    `opps_made_1` SMALLINT NULL,
    `opps_2` SMALLINT NULL,
    `opps_made_2` SMALLINT NULL,
    `opps_3` SMALLINT NULL,
    `opps_made_3` SMALLINT NULL,
    `opps_4` SMALLINT NULL,
    `opps_made_4` SMALLINT NULL,
    `opps_5` SMALLINT NULL,
    `opps_made_5` SMALLINT NULL,
    `framing` DOUBLE NULL,
    `arm` DOUBLE NULL,
    `zr` DOUBLE NULL,

    PRIMARY KEY (`player_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `players_career_pitching_stats` (
    `player_id` INTEGER NOT NULL,
    `year` SMALLINT NULL,
    `team_id` INTEGER NULL,
    `game_id` INTEGER NULL,
    `league_id` INTEGER NULL,
    `level_id` SMALLINT NULL,
    `split_id` SMALLINT NULL,
    `ip` SMALLINT NULL,
    `ab` SMALLINT NULL,
    `tb` SMALLINT NULL,
    `ha` SMALLINT NULL,
    `k` SMALLINT NULL,
    `bf` SMALLINT NULL,
    `rs` SMALLINT NULL,
    `bb` SMALLINT NULL,
    `r` SMALLINT NULL,
    `er` SMALLINT NULL,
    `gb` SMALLINT NULL,
    `fb` SMALLINT NULL,
    `pi` SMALLINT NULL,
    `ipf` SMALLINT NULL,
    `g` SMALLINT NULL,
    `gs` SMALLINT NULL,
    `w` SMALLINT NULL,
    `l` SMALLINT NULL,
    `s` SMALLINT NULL,
    `sa` SMALLINT NULL,
    `da` SMALLINT NULL,
    `sh` SMALLINT NULL,
    `sf` SMALLINT NULL,
    `ta` SMALLINT NULL,
    `hra` SMALLINT NULL,
    `bk` SMALLINT NULL,
    `ci` SMALLINT NULL,
    `iw` SMALLINT NULL,
    `wp` SMALLINT NULL,
    `hp` SMALLINT NULL,
    `gf` SMALLINT NULL,
    `dp` SMALLINT NULL,
    `qs` SMALLINT NULL,
    `svo` SMALLINT NULL,
    `bs` SMALLINT NULL,
    `ra` SMALLINT NULL,
    `cg` SMALLINT NULL,
    `sho` SMALLINT NULL,
    `sb` SMALLINT NULL,
    `cs` SMALLINT NULL,
    `hld` SMALLINT NULL,
    `ir` DOUBLE NULL,
    `irs` DOUBLE NULL,
    `wpa` DOUBLE NULL,
    `li` DOUBLE NULL,
    `stint` SMALLINT NULL,
    `outs` SMALLINT NULL,
    `sd` SMALLINT NULL,
    `md` SMALLINT NULL,
    `war` DOUBLE NULL,
    `ra9war` DOUBLE NULL,

    PRIMARY KEY (`player_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `players_fielding` (
    `player_id` INTEGER NOT NULL,
    `team_id` INTEGER NULL,
    `league_id` INTEGER NULL,
    `position` SMALLINT NULL,
    `role` SMALLINT NULL,
    `fielding_ratings_infield_range` SMALLINT NULL,
    `fielding_ratings_infield_arm` SMALLINT NULL,
    `fielding_ratings_turn_doubleplay` SMALLINT NULL,
    `fielding_ratings_outfield_range` SMALLINT NULL,
    `fielding_ratings_outfield_arm` SMALLINT NULL,
    `fielding_ratings_catcher_arm` SMALLINT NULL,
    `fielding_ratings_catcher_ability` SMALLINT NULL,
    `fielding_ratings_infield_error` SMALLINT NULL,
    `fielding_ratings_outfield_error` SMALLINT NULL,
    `fielding_experience0` SMALLINT NULL,
    `fielding_experience1` SMALLINT NULL,
    `fielding_experience2` SMALLINT NULL,
    `fielding_experience3` SMALLINT NULL,
    `fielding_experience4` SMALLINT NULL,
    `fielding_experience5` SMALLINT NULL,
    `fielding_experience6` SMALLINT NULL,
    `fielding_experience7` SMALLINT NULL,
    `fielding_experience8` SMALLINT NULL,
    `fielding_experience9` SMALLINT NULL,
    `fielding_rating_pos1` SMALLINT NULL,
    `fielding_rating_pos2` SMALLINT NULL,
    `fielding_rating_pos3` SMALLINT NULL,
    `fielding_rating_pos4` SMALLINT NULL,
    `fielding_rating_pos5` SMALLINT NULL,
    `fielding_rating_pos6` SMALLINT NULL,
    `fielding_rating_pos7` SMALLINT NULL,
    `fielding_rating_pos8` SMALLINT NULL,
    `fielding_rating_pos9` SMALLINT NULL,

    PRIMARY KEY (`player_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `players_pitching` (
    `player_id` INTEGER NOT NULL,
    `team_id` INTEGER NULL,
    `league_id` INTEGER NULL,
    `position` SMALLINT NULL,
    `role` SMALLINT NULL,
    `pitching_ratings_overall_stuff` SMALLINT NULL,
    `pitching_ratings_overall_control` SMALLINT NULL,
    `pitching_ratings_overall_movement` SMALLINT NULL,
    `pitching_ratings_overall_balk` SMALLINT NULL,
    `pitching_ratings_overall_hp` SMALLINT NULL,
    `pitching_ratings_overall_wild_pitch` SMALLINT NULL,
    `pitching_ratings_vsr_stuff` SMALLINT NULL,
    `pitching_ratings_vsr_control` SMALLINT NULL,
    `pitching_ratings_vsr_movement` SMALLINT NULL,
    `pitching_ratings_vsr_balk` SMALLINT NULL,
    `pitching_ratings_vsr_hp` SMALLINT NULL,
    `pitching_ratings_vsr_wild_pitch` SMALLINT NULL,
    `pitching_ratings_vsl_stuff` SMALLINT NULL,
    `pitching_ratings_vsl_control` SMALLINT NULL,
    `pitching_ratings_vsl_movement` SMALLINT NULL,
    `pitching_ratings_vsl_balk` SMALLINT NULL,
    `pitching_ratings_vsl_hp` SMALLINT NULL,
    `pitching_ratings_vsl_wild_pitch` SMALLINT NULL,
    `pitching_ratings_talent_stuff` SMALLINT NULL,
    `pitching_ratings_talent_control` SMALLINT NULL,
    `pitching_ratings_talent_movement` SMALLINT NULL,
    `pitching_ratings_talent_balk` SMALLINT NULL,
    `pitching_ratings_talent_hp` SMALLINT NULL,
    `pitching_ratings_talent_wild_pitch` SMALLINT NULL,
    `pitching_ratings_pitches_fastball` SMALLINT NULL,
    `pitching_ratings_pitches_slider` SMALLINT NULL,
    `pitching_ratings_pitches_curveball` SMALLINT NULL,
    `pitching_ratings_pitches_screwball` SMALLINT NULL,
    `pitching_ratings_pitches_forkball` SMALLINT NULL,
    `pitching_ratings_pitches_changeup` SMALLINT NULL,
    `pitching_ratings_pitches_sinker` SMALLINT NULL,
    `pitching_ratings_pitches_splitter` SMALLINT NULL,
    `pitching_ratings_pitches_knuckleball` SMALLINT NULL,
    `pitching_ratings_pitches_cutter` SMALLINT NULL,
    `pitching_ratings_pitches_circlechange` SMALLINT NULL,
    `pitching_ratings_pitches_knucklecurve` SMALLINT NULL,
    `pitching_ratings_pitches_talent_fastball` SMALLINT NULL,
    `pitching_ratings_pitches_talent_slider` SMALLINT NULL,
    `pitching_ratings_pitches_talent_curveball` SMALLINT NULL,
    `pitching_ratings_pitches_talent_screwball` SMALLINT NULL,
    `pitching_ratings_pitches_talent_forkball` SMALLINT NULL,
    `pitching_ratings_pitches_talent_changeup` SMALLINT NULL,
    `pitching_ratings_pitches_talent_sinker` SMALLINT NULL,
    `pitching_ratings_pitches_talent_splitter` SMALLINT NULL,
    `pitching_ratings_pitches_talent_knuckleball` SMALLINT NULL,
    `pitching_ratings_pitches_talent_cutter` SMALLINT NULL,
    `pitching_ratings_pitches_talent_circlechange` SMALLINT NULL,
    `pitching_ratings_pitches_talent_knucklecurve` SMALLINT NULL,
    `pitching_ratings_misc_velocity` SMALLINT NULL,
    `pitching_ratings_misc_arm_slot` SMALLINT NULL,
    `pitching_ratings_misc_stamina` SMALLINT NULL,
    `pitching_ratings_misc_ground_fly` SMALLINT NULL,
    `pitching_ratings_misc_hold` SMALLINT NULL,

    PRIMARY KEY (`player_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `teams` (
    `team_id` INTEGER NOT NULL,
    `name` VARCHAR(50) NULL,
    `abbr` VARCHAR(50) NULL,
    `nickname` VARCHAR(50) NULL,
    `logo_file_name` VARCHAR(200) NULL,
    `city_id` INTEGER NULL,
    `park_id` INTEGER NULL,
    `league_id` INTEGER NULL,
    `sub_league_id` INTEGER NULL,
    `division_id` INTEGER NULL,
    `nation_id` INTEGER NULL,
    `parent_team_id` INTEGER NULL,
    `level` INTEGER NULL,
    `prevent_any_moves` TINYINT NULL,
    `human_team` TINYINT NULL,
    `human_id` INTEGER NULL,
    `gender` INTEGER NULL,
    `background_color_id` VARCHAR(8) NULL,
    `text_color_id` VARCHAR(8) NULL,
    `ballcaps_main_color_id` VARCHAR(8) NULL,
    `ballcaps_visor_color_id` VARCHAR(8) NULL,
    `jersey_main_color_id` VARCHAR(8) NULL,
    `jersey_away_color_id` VARCHAR(8) NULL,
    `jersey_secondary_color_id` VARCHAR(8) NULL,
    `jersey_pin_stripes_color_id` VARCHAR(8) NULL,
    `allstar_team` TINYINT NULL,
    `historical_id` VARCHAR(50) NULL,

    PRIMARY KEY (`team_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `players` ADD CONSTRAINT `players_team_id_fkey` FOREIGN KEY (`team_id`) REFERENCES `teams`(`team_id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `players_batting` ADD CONSTRAINT `players_batting_team_id_fkey` FOREIGN KEY (`team_id`) REFERENCES `teams`(`team_id`) ON DELETE SET NULL ON UPDATE CASCADE;

